# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


production:
  GOOGLE_CLIENT_ID: '876689863937-ucfo4a2p29kml4lpishfof1oka9f9tmr.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET: 'R2q9QfRppMNUwarFqUCf8FhT'
  FACEBOOK_CLIENT_ID: '118207755486069'
  FACEBOOK_CLIENT_SECRET: 'd623740f037c793a844c41effde47926'

development:
  GOOGLE_CLIENT_ID: '876689863937-ucfo4a2p29kml4lpishfof1oka9f9tmr.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET: 'R2q9QfRppMNUwarFqUCf8FhT'
  FACEBOOK_CLIENT_ID: '118207755486069'
  FACEBOOK_CLIENT_SECRET: 'd623740f037c793a844c41effde47926'
